export { default as App } from './app'
export { default as Home } from './home'
export { default as Detail } from './detail'
export { About } from './about'
export { NotFound } from './not-found'
export { default as Login } from './login'
export { default as Message } from './message'
export { default as User } from './user'
export { default as Post } from './post'
export { default as Hint } from './hint'
